//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeBuilderProject.EDMXModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int IDEdu { get; set; }
        public string University { get; set; }
        public string TitleofDiploma { get; set; }
        public string Degree { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public Nullable<int> IDPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
