//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeBuilderProject.EDMXModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectResumeEntities : DbContext
    {
        public ProjectResumeEntities()
            : base("name=ProjectResumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
    }
}
